pipeline:

  test:
    image: node:6
    secrets:
      - npm_config__auth
      - npm_config_registry
    environment:
      - NPM_CONFIG_ALWAYS_AUTH=true
    commands:
      - npm i
      - npm test
    when:
      event: [push, pull_request, tag]

  publish_to_artifactory:
    image: node:6
    secrets:
      - npm_config__auth
      - npm_config_registry
    environment:
      - NPM_CONFIG_ALWAYS_AUTH=true
    commands:
      - npm publish
    when:
      event: [tag]

matrix:
  NPM_CONFIG_USERNAME:
    - regt-build-bot